### ISSUE TITLE
Error during installation of ctmicro

### ISSUE THREAD

**Issue by HadiEbrahimiHaratameh** [microcombustion/ctmicro#1]
Dear Professor,
When I wanted to install ctmicro by this command in terminal (Ubuntu):

**sudo conda create -n ctmicro -c cantera/label/dev libcantera-devel cantera numpy scipy jupyter cython**

, the following error was appeared:
....
WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/hadi/anaconda3/pkgs/qtpy-1.9.0-py_0/site-packages/qtpy/Qt3DCore.py.  Please remove this file manually (you may need to reboot to free file handles)
WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/hadi/anaconda3/pkgs/qtpy-1.9.0-py_0/site-packages/qtpy/QtWebEngineWidgets.py.  Please remove this file manually (you may need to reboot to free file handles)
WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/hadi/anaconda3/pkgs/qtpy-1.9.0-py_0/site-packages/qtpy/__init__.py.  Please remove this file manually (you may need to reboot to free file handles)
qtpy-1.9.0           | 38 KB     | ######################################################################################## | 100% 

InvalidArchiveError('Error with archive /home/hadi/anaconda3/pkgs/prometheus_client-0.7.1-py_09nqhcq4v/info-prometheus_client-0.7.1-py_0.tar.zst.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCould not unlink')
InvalidArchiveError('Error with archive /home/hadi/anaconda3/pkgs/ipywidgets-7.5.1-py_08p_qzden/info-ipywidgets-7.5.1-py_0.tar.zst.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCould not unlink')
InvalidArchiveError('Error with archive /home/hadi/anaconda3/pkgs/defusedxml-0.6.0-py_0lazibncl/info-defusedxml-0.6.0-py_0.tar.zst.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCould not unlink')
InvalidArchiveError('Error with archive /home/hadi/anaconda3/pkgs/qtpy-1.9.0-py_07nhpm2bm/info-qtpy-1.9.0-py_0.tar.zst.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCould not unlink')

Could you help me to solve the problem?
Thank you
Hadi

**Comment by ischoegl** [comment]
Not sure, but this appears to be related to conda (I.e. the creation of the Python environment) - except for the development branch of Cantera, I’m using all standard packages, i.e. all of this appears to be upstream. I’m personally using miniconda (instead of anaconda) as the base, but I doubt that this is the issue.

**Comment by ischoegl** [comment]
PS: you could try to run `conda update --all` ... also, I don`t run conda using sudo

**Comment by HadiEbrahimiHaratameh** [comment]
Dear Professor,
Now, it work. I see in "test1d.csv" both T and Tw. That is perfect.
(Another problem occurred, too: Not Access to Anaconda3 which  was solved by:
 sudo chown -R hadi: /home/hadi/anaconda2)

Yours Sincerely,
Hadi Ebrahimi

**Comment by ischoegl** [comment]
Glad it worked. :+1:
